blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.home, name='blog-home'),
	path('about/', views.about, name='blog-about'),
	path('folderview/<path:folderpath>',views.folderview,name='blog-folderview'),
	path('create/<path:folderpath>',views.create_file_in_folder,name='blog-create_file_in_folder'),
]

django_project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('ide/', user_views.simple, name='ide'),
    path('', include('blog.urls')),
    path('CodeFiles/<path:filepath>',user_views.codeviewer, name='codeviewer'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	image = models.ImageField(default='default.jpg', upload_to='profile_pics')

	def __str__(self):
		return f'{self.user.username} Profile'

	def save(self, *args, **kawrgs):
		super().save(*args, **kawrgs)

		img = Image.open(self.image.path)

		if img.height > 300 or img.width > 300:
			output_size = (300, 300)
			img.thumbnail(output_size)
			img.save(self.image.path)


class Snippet(models.Model):
	text = models.TextField()
	created_at = models.DateTimeField(auto_now_add=True)

	class Meta:
		ordering = ('-created_at', )

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile
from .models import Snippet
from django_ace import AceWidget


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']


class SnippetForm(forms.ModelForm):
    class Meta:
        model = Snippet
        widgets = {
            "text": AceWidget(mode='javascript', theme='monokai'),
        }
        exclude = ()

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from .forms import SnippetForm
from django.views.decorators.csrf import csrf_exempt
import os, subprocess


class node():
    def __init__(self,name,stat):
        self.name = name
        self.stat = stat
        self.child = []
        self.path= name
    def add_child(self,child_node):
        self.child.append(child_node)
        child_node.path = self.path+"/"+child_node.path

top = node('c_directory','dir')
def builder(top):
    curr = list(os.popen('ls'))

    for i in range(len(curr)):
        curr[i]= curr[i].strip()
        dir_check = os.path.isdir(curr[i])
        if(dir_check):
            new_dir=node(curr[i],'dir')
            os.chdir(curr[i])
            builder(new_dir)
            os.chdir('..')
            top.add_child(new_dir)
        else:
            new_file=node(curr[i],'file')
            top.add_child(new_file)




def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Your account has been created!')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})


@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)

        if u_form.is_valid and p_form.is_valid:
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('profile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form' : u_form,
        'p_form' : p_form
    }

    return render(request, 'users/profile.html', context)


@login_required
@csrf_exempt
def simple(request):
    output = ""
    input_data = ""
    initial_val = ""
    if request.method == 'POST':
        form = SnippetForm(request.POST)

        if form.is_valid():
            newcode = request.POST['text']
            button = request.POST.get('pressed', False)
            input_data = request.POST['input']
            initial_val = newcode

            if(button == "Compile and run"):
                os.chdir("./CodeFiles")

                os.popen("touch test.cpp")
                f = open("test.cpp", 'w')
                f.write(newcode)
                f.close()

                p1 = subprocess.run(['g++', 'test.cpp'], capture_output=True, text=True)

                if p1.returncode == 0:
                    p2 = subprocess.run(['./a.out'], capture_output=True, text=True, input=input_data)

                    if p2.returncode == 0:
                        output = p2.stdout
                    else:
                        output = "Some error in code :("
                else:
                    output = "Compilation Error :("

                os.chdir("..")

        return render(request, "snippets.html", {
        "form": form,
        "initial_val": initial_val,
        "lang": "c_cpp",
        "output": output,
        "inp_Data": input_data,
        })

    else:
        form = SnippetForm()
    return render(request, "snippets.html", {
        "form": form,
        "initial_val": "",
        "lang": "c_cpp",
        "output": "",
        "inp_Data": "",
    })


@login_required
@csrf_exempt
def codeviewer(request, filepath):

    file_path = "./CodeFiles/"+filepath

    initial_dir = os.getcwd()
    i = len(file_path)-1
    while i >= 0:
        if(file_path[i] == '/'):
            break
        i = i-1

    parent_dir = file_path[:i]
    file_name = file_path[i+1:]

    f = open(file_path, 'r')
    initial_val = f.read()

    print(initial_val)
    f.close()
    i = len(file_path)-1
    while i >= 0:
        if(file_path[i] == '.'):
            break
        i = i - 1
    lang = file_path[i+1:]
    if(lang == "cpp"):
        lang = "c_cpp"
    elif lang == "py":
        lang = "python"
    elif lang == "java":
        lang = "java"
    else:
        lang = "text"

    print(lang)

    output = "Run the code First"
    input_data = "enter you input here"

    if request.method == 'POST':
        form = SnippetForm(request.POST)
    
        if form.is_valid():
            newcode = request.POST['text']
            button = request.POST.get('pressed', False)
            input_data = request.POST['input']

            if(button == "Save"):
                f = open(file_path, 'w')
                f.write(newcode)
                f.close()
                f = open(file_path, 'r')
                initial_val = f.read()
                f.close()

            else:
                os.chdir(parent_dir)

                if lang == "c_cpp":
                    p1 = subprocess.run(['g++', file_name], capture_output=True, text=True)

                    if p1.returncode == 0:
                        p2 = subprocess.run(['./a.out'], capture_output=True, text=True, input=input_data)

                        if p2.returncode == 0:
                            output = p2.stdout
                        else:
                            output = "Some error in code :("
                    else:
                        output = "Compilation Error :("
                    
                    p3 = subprocess.run(['rm', 'a.out'])
                    if p3.returncode == 0:
                        print("file delete successfull")
                    else:
                        print(p3.stderr)

                elif lang == "python":
                    p1 = subprocess.run(['python3', file_name], capture_output=True, text=True, input=input_data)

                    if p1.returncode == 0:
                        output = p1.stdout
                    else:
                        output = "there is some error in the code"
                elif lang == "java":
                    p1 = subprocess.run(['javac', file_name], capture_output=True, text=True)

                    if p1.returncode == 0:
                        p2 = subprocess.run(['java', file_name[:-5]], capture_output=True, text=True, input=input_data)
                        if p2.returncode == 0:
                            output = p2.stdout
                        else:
                            output = "Some error in code :("
                    else:
                        output = "Compilation Error :("

                    p3 = subprocess.run(['rm', file_name[:-5]+".class"])

                os.chdir(initial_dir)

        f = open(file_path, 'r')
        initial_val = f.read()
        f.close()

        return render(request, "snippets.html", {
        "form": form,
        "initial_val": initial_val,
        "lang": lang,
        "output": output,
        "inp_Data": input_data,
        })

    else:
        form = SnippetForm()
    return render(request, "snippets.html", {
        "form": form,
        "initial_val": initial_val,
        "lang": lang,
        "output": output,
        "inp_Data": input_data,
    })

users/templates/snippets.html
{% extends "blog/base.html" %}
{% block content %}
<main role="main" class="container">
    <div class="row">
      <div class="col-md-8">
    
    <link href="/static/django_ace/widget.css" type="text/css" media="screen" rel="stylesheet">
    <script src="/static/django_ace/ace/ace.js"></script>
    <script src="/static/django_ace/widget.js"></script>
    <script src="/static/django_ace/ace/mode-javascript.js"></script>
    <script src="/static/django_ace/ace/mode-c_cpp.js"></script>
    <script src="/static/django_ace/ace/mode-python.js"></script>
    <script src="/static/django_ace/ace/mode-java.js"></script>
    <script src="/static/django_ace/ace/theme-monokai.js"></script>
        
    <form action="" method="post">
        <input type="hidden" name="csrfmiddlewaretoken" value="Jb4p2MSLXHLrSl2HetM7t6OA0hs5tpFTdtbwuwCqEB8jslSXjirM56NTORdnDyVZ">

        <label for="id_text"><h3>Write Your Code Here:</h3></label> <div class="django-ace-editor"><div style="width: 500px" class="django-ace-toolbar"><a href="./"      class="django-ace-max_min"></a></div><div class="django-ace-widget loading" data-behaviours="true" data-mode={{lang}} data-readonly="false"        data-showgutter="true" data-showinvisibles="false" data-showprintmargin="true" data-theme="monokai" data-usesofttabs="true" style="width:1200px;        height:400px"><div></div></div><textarea name="text" cols="40" rows="10" required id="id_text">{{initial_val}}</textarea></div>


        <input type="submit"  name ="pressed" value="Save" />
        <input type="submit" name="pressed" value="Compile and run" />
        
        <br><br>
        <h3>Type Your input here</h3>
        <div class="django-ace-editor"><div style="width: 500px" class="django-ace-toolbar"><a href="./"      class="django-ace-max_min"></a></div><div class="django-ace-widget loading" data-behaviours="true" data-mode=text data-readonly="false"        data-showgutter="true" data-showinvisibles="false" data-showprintmargin="true" data-theme="monokai" data-usesofttabs="true" style="width:1200px;        height:100px"><div></div></div><textarea name="input" id="inp" cols="40" rows="10">{{ inp_Data }}</textarea></div>


        <br><br>
        <h3>Your Output is</h3>
        <div class="django-ace-editor"><div style="width: 500px" class="django-ace-toolbar"><a href="./"      class="django-ace-max_min"></a></div><div class="django-ace-widget loading" data-behaviours="true" data-mode=text data-readonly="true"        data-showgutter="true" data-showinvisibles="false" data-showprintmargin="true" data-theme="monokai" data-usesofttabs="true" style="width:1200px;        height:100px"><div></div></div><textarea name="output" cols="40" rows="10">{{ output }}</textarea></div>


    </form>

            </div>
        </div>
    </main>
{% endblock content %}